resolver: lts-13.9

packages:
- .

extra-deps:
- hashing-0.1.0.1
- monadlist-0.0.2
- ref-tf-0.4.0.1
- hnix-store-core-0.1.0.0
- git: https://github.com/haskell-nix/hnix.git
  commit: e7df5e1bd9ae91ab103605ce21d5d71309346326
